from torchvision.models.alexnet import *
from torchvision.models.vgg import *
from torchvision.models.squeezenet import *
from torchvision.models.inception import *
from torchvision.models.densenet import *
from torchvision.models.googlenet import *
from .architectures.mobilenet.mobilenetv3 import *
from .architectures.efficientnet import *
from .architectures.moco.moco_resnet import *
from .architectures.swav.swav_resnet import *
from .architectures.simclr.simclr_resnet import *
